# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a746a62c64d7d648d6fb19f4a6bd4dd9cfae2d51557021b03d86b44c6434f139bdb6f5c579213fc5930a935cba5ee613eaf1f89e95c25a76b045d8e5f02c37a

test:
  secret_key_base: 30be2fc9521c191d13d45ce9169a13116888bf5151a5619bdcf769bd67767080bb1a964ac13fe392345c1fcced7fbf66ac4603bdebde83738165d83412667e7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
